import { Fragment } from "react";
import MainNav from "../navigationsAndFooters/mainNav";
import Style from './main.module.css';

import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import CardSlider from "../overalTools/cardSlider";



const Main = () =>{
    return(
        <Fragment>
            <MainNav></MainNav>
            <div className={Style.container}>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <article>
                    <p className={Style.example_left}>XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL XCAPITAL</p> 
                </article>
                <div className={Style.overlay}></div>
                <div className={Style.onTopText}>
                    <div>
                        <h1>X-CAPITAL</h1>
                    </div>
                    <div>
                        <h2>endless possibilities</h2>
                    </div>
                </div>
                <div className={Style.aboutUs}>
                    <div>
                        <h3>چیه؟ویدیو پایینو ببین X-CAPITAL میخوای بدونی دقیقا</h3>
                    </div>
                    <div className={Style.playBtnDiv}>
                        <button><span>نمایش ویدیو</span><PlayArrowIcon sx={{borderLeft:'solid 2px black' , padding:'0px'}}></PlayArrowIcon></button>
                    </div>
                </div>
            </div>
            <div>
                <CardSlider tile='تست'></CardSlider>
            </div>
        </Fragment>
    )
}
export default Main;